### ISSUE TITLE
What are the Dependencies?

### ISSUE THREAD

**Issue by E3V3A** [europa502/shARP_2.0#2]
Hi! Nice tool. 
What are the dependencies, if any?
(Please update README.)

**Comment by europa502** [comment]
Sorry for the late reply. Please refer https://github.com/europa502/shARP . Everyting is updated there. This repo will soon be removed.

**Comment by europa502** [comment]
Still incase you want to know .. these ate the dependencies- 
1. Python 2.7.x
2. Aircrack-ng
3. espeak (optional)
